### ISSUE TITLE
Roadmap of MMYOLO

### ISSUE THREAD

**Issue by hhaAndroid** [open-mmlab/mmyolo#136]
We keep this issue open to collect feature requests from users and hear your voice. Our monthly release plan is also available here.

You can either:

1. Suggest a new feature by leaving a comment.
2. Vote for a feature request with +1 or be against with -1. (Remember that developers are busy and cannot respond to all feature requests, so vote for your most favorable one!)
3. Tell us that you would like to help implement one of the features in the list or review the PRs. (This is the greatest things to hear about!)

## V0.2.0 (2022.10)

- [ ] Align `YOLOv6` training mAP
- [ ] Align `PPYOLOE/YOLOv7` testing mAP
- [ ] Support deployment based on MMDeploy
- [ ] `YOLOv5` supports the `VOC` dataset https://github.com/open-mmlab/mmyolo/pull/134
- [ ] Refactor the Neck model structure to make it easier to use
- [ ] Optimize and refine `image_demo.py` https://github.com/open-mmlab/mmyolo/pull/128
- [ ] The `albu`  library used in the `YOLOv5` algorithm supports any version
- [ ] `user_guides/yolov5_tutorial.md` translate to English

**Comment by vansin** [comment]
Support deployment based on MMDeploy

**Comment by RangeKing** [comment]
Added a script to verify whether the installation was successful

**Comment by PeterH0323** [comment]
Pick: Align `YOLOv6` training mAP

**Comment by xin-li-67** [comment]
pick: user_guides/yolov5_tutorial.md translate to English.

**Comment by ztyf-lq** [comment]
Optimize and refine image_demo.py https://github.com/open-mmlab/mmyolo/pull/128

**Comment by Zheng-LinXiao** [comment]
YOLOv5 supports the VOC dataset https://github.com/open-mmlab/mmyolo/pull/134

**Comment by Nioolek** [comment]
Pick: Align `ppyoloe` testing mAP: PR #145

**Comment by xin-li-67** [comment]
Add a script to support to convert yolo-style *.txt format to coco in PR#161

**Comment by RangeKing** [comment]
中文视频资源建议
[基础类第 x 期] 如何优雅地使用 MMYOLO 训练自定义数据集

**Comment by PeterH0323** [comment]
Pick : [基础类第 x 期] 如何优雅地使用 MMYOLO 训练自定义数据集

**Comment by Seperendity** [comment]
Can you post a video tutorial on how to customize module embedding into the network? Take the Transformer module in the original yolov5 library for example, how to integrate the module designed by myself into the network. I want to do a series of experiments based on mmyolo, but don't konw how to modify the file clearly.

**Comment by fcakyon** [comment]
Are you planning to support yolov6 and yolov5 training?

**Comment by PeterH0323** [comment]
> Are you planning to support `yolov5` 1280 model, `yolov6` m/l model and `yolov7` training?

Hi @fcakyon 
All you mention were already in progress, will release soon😄

**Comment by fcakyon** [comment]
> > Are you planning to support `yolov5` 1280 model, `yolov6` m/l model and `yolov7` training?
> 
> Hi @fcakyon All you mention were already in progress, will release soon😄

Great news! I am the maintainer of [sahi](https://github.com/obss/sahi), can wait to support mmyolo 💯

**Comment by PeterH0323** [comment]
> > > Are you planning to support `yolov5` 1280 model, `yolov6` m/l model and `yolov7` training?
> > 
> > 
> > Hi @fcakyon All you mention were already in progress, will release soon😄
> 
> Great news! I am the maintainer of [sahi](https://github.com/obss/sahi), can wait to support mmyolo once these features are released 💯

Hi @fcakyon 
I am the one who want to support sahi in MMYOLO, What a coincidence ! We can keep in touch 😄

**Comment by fcakyon** [comment]
> Hi @fcakyon I am the one who want to support sahi in MMYOLO, What a coincidence ! We can keep in touch 😄

Wow, great coincidence 😮  Let's keep in touch 🚀

**Comment by hhaAndroid** [comment]
> > Hi @fcakyon I am the one who want to support sahi in MMYOLO, What a coincidence ! We can keep in touch smile
> 
> Wow, great coincidence open_mouth Let's keep in touch rocket

Hi, We plan to integrate sahi in v0.1.3. The current plan is:

1. First make a draft in mmyolo to see the generality
2. If the generality is very strong, we can consider submitting PR directly to mmengine so that all openmmlab repo can be used directly

how do you feel? @fcakyon

**Comment by fcakyon** [comment]
@hhaAndroid sounds great! What is your implementation plan? Do you want to include it as a tool or as a separate model? How can I help you with this?

**Comment by hhaAndroid** [comment]
> @hhaAndroid sounds great! What is your implementation plan? Do you want to include it as a tool or as a separate model? How can I help you with this?

Let's open an issue to discuss!

**Comment by zcunyi** [comment]
Can you arrange an urgent arrangement for yolo-pose?

**Comment by xin-li-67** [comment]
> Can you arrange an urgent arrangement for yolo-pose?

Hi~ For yolo-pose, are you referring the yolo-pose from the texas instruments or another version? If there is a specific version you would like MMYOLO to be integrated, can you add a comment in  [issue#233](https://github.com/open-mmlab/mmyolo/issues/233) ? Thx!!

**Comment by RangeKing** [comment]
Add more result analysis functions. Refer to https://github.com/dbolya/tide.

**Comment by RangeKing** [comment]
> I want to use the model implemented by mmyolo in the config file that I have implemented through mmdetection. For example, I want to add one of mmyolo's backbones to the complete model defined by mmdetection. Is it possible? What should I do?

Hi @chihuajiao, sorry for the late reply. You could refer to the [tutorial](https://mmyolo.readthedocs.io/en/latest/advanced_guides/how_to.html#replace-the-backbone-network) to implemente it.

**Comment by SicongLiu998** [comment]
Hi! I found that both MMYOLO and MMDetection contains implementations of YOLQX-s. What are the differences between the two. In our experiments, the AP-10K data set in MMPose, which also contains bounding boxes information like COCO are applied. But there is a big gap between the results of MMYOLO and MMetection. I would like to know the differences between the two implementations. Thanks a lot for your time!

**Comment by xin-li-67** [comment]
> Hi! I found that both MMYOLO and MMDetection contains implementations of YOLQX-s. What are the differences between the two. In our experiments, the AP-10K data set in MMPose, which also contains bounding boxes information like COCO are applied. But there is a big gap between the results of MMYOLO and MMetection. I would like to know the differences between the two implementations. Thanks a lot for your time!

Hi, I could only say something about the MMPose bbox detection you mentioned. Most of the algorithms you could find in MMPose are two-stage heatmap detections, which require human bboxes detection in their first stage. That's why there is COCO bbox information used in the implementations.

**Comment by SicongLiu998** [comment]
> > Hi! I found that both MMYOLO and MMDetection contains implementations of YOLQX-s. What are the differences between the two. In our experiments, the AP-10K data set in MMPose, which also contains bounding boxes information like COCO are applied. But there is a big gap between the results of MMYOLO and MMetection. I would like to know the differences between the two implementations. Thanks a lot for your time!
> 
> Hi, I could only say something about the MMPose bbox detection you mentioned. Most of the algorithms you could find in MMPose are two-stage heatmap detections, which require human bboxes detection in their first stage. That's why there is COCO bbox information used in the implementations.

Thanks for your reply ! I may not explain my question clearly. I actually know that two main paradigms of pose estimation. I would like to use MMYolo or MMDetection to finish the animal object detection task. I just use the AP-10K data set supplied in MMPose that support the same format like COCO. I used YoloX-s to finish the object detection by MMDetection and MMYolo respectively. The results of the two frame work should be very close but in fact there is a big gap between the two results, about 10 AP. I guess that there are some differences in implementations of YoloX-s between the two object detection frame work.

**Comment by xin-li-67** [comment]
> > > Hi! I found that both MMYOLO and MMDetection contains implementations of YOLQX-s. What are the differences between the two. In our experiments, the AP-10K data set in MMPose, which also contains bounding boxes information like COCO are applied. But there is a big gap between the results of MMYOLO and MMetection. I would like to know the differences between the two implementations. Thanks a lot for your time!
> > 
> > 
> > Hi, I could only say something about the MMPose bbox detection you mentioned. Most of the algorithms you could find in MMPose are two-stage heatmap detections, which require human bboxes detection in their first stage. That's why there is COCO bbox information used in the implementations.
> 
> Thanks for your reply ! I may not explain my question clearly. I actually know that two main paradigms of pose estimation. I would like to use MMYolo or MMDetection to finish the animal object detection task. I just use the AP-10K data set supplied in MMPose that support the same format like COCO. I used YoloX-s to finish the object detection by MMDetection and MMYolo respectively. The results of the two frame work should be very close but in fact there is a big gap between the two results, about 10 AP. I guess that there are some differences in implementations of YoloX-s between the two object detection frame work.

Well, I still can't tell why there is such a difference on your results. For the YOLOX implementations in MMDet and MMYOLO, the only difference is on the `mosaic` part, which you could check [here](https://github.com/open-mmlab/mmdetection/blob/92d03df639a099c7263805a859923e2f0815e381/mmdet/datasets/transforms/transforms.py#L2063) and [here](https://github.com/open-mmlab/mmyolo/blob/e62c8c4593702d23e5a75d940d9158aa4ea418ae/mmyolo/datasets/transforms/mix_img_transforms.py#L186). If you still have questions on the implementation and final performance, you are welcomed to open a new issue with your benchmark table so that the maintainers may be able to find out more details.

**Comment by Bovey0809** [comment]
I implemented yolox-pose based on mmyolo here, https://github.com/Bovey0809/mmyolo-pose

**Comment by SicongLiu998** [comment]
> I implemented yolox-pose based on mmyolo here, https://github.com/Bovey0809/mmyolo-pose

That is a pretty good job !

**Comment by arkerman** [comment]
Hi !
Does mmyolo support for mmselfsup ?
 I wanna use moco to self_supervise train a pretrained model .
 And then use the pretrained model on yolov5 . Does this shit can be realized ？

**Comment by RangeKing** [comment]
> Hi !
> Does mmyolo support for mmselfsup ?
>  I wanna use moco to self_supervise train a pretrained model .
>  And then use the pretrained model on yolov5 . Does this shit can be realized ？

Hi，@arkerman 
Of course, MMYOLO supports for MMSelfsup. Here's the example, https://mmyolo.readthedocs.io/en/latest/recommended_topics/replace_backbone.html#use-backbone-network-implemented-in-mmselfsup.

**Comment by www516717402** [comment]
Add distillation example in yolo serial

**Comment by RangeKing** [comment]
> Add distillation example in yolo serial

Hi @www516717402, here's a distillation example of RTMDet,
https://github.com/open-mmlab/mmyolo/tree/main/configs/rtmdet/distillation.

**Comment by LorenzoSun-V** [comment]
> ## V0.5.0(2023.1)
> * [ ]  code
>   
>   * [ ]  Support YOLOv8 instance seg (YOLOv8 支持实例分割)
>   * [ ]  Added a script to verify whether the installation was successful (新增快速验证是否安装成功的脚本) [[Feature] Add a script to verify whether the installation was successful  #487](https://github.com/open-mmlab/mmyolo/pull/487)

Hi, does mmyolo support YOLOv8 ins-seg now? When will it support if not yet?  I just saw a [commit](https://github.com/open-mmlab/mmyolo/commit/c0d1468ba8d1f9b225055a3b4f81875465e90a22) and failed to train YOLOv8 ins-seg model following the code in this commit. :sob:

**Comment by nik123** [comment]
What is the current state of yolov8 ins-seg support? Is it in progress or the plans for support of yolov8 were abandoned?

**Comment by mohamedrekik** [comment]
Add quantization for MMYOLO will be a great feature. YOLO is already fast and relatively accurate. But, with quantization techniques (like Int8, ...), it will be much more powerful !

**Comment by zsy7532** [comment]
> > 我想在我通过 mmdetection 实现的配置文件中使用 mmyolo 实现的模型。例如，我想将 mmyolo 的一个主干添加到由 mmdetection 定义的完整模型中。可能吗？我该怎么办？
> 
> 嗨，很抱歉回复晚了。您可以参考[教程](https://mmyolo.readthedocs.io/en/latest/advanced_guides/how_to.html#replace-the-backbone-network)来实现它。

Hi, the link is not available, could you offer a new link about how to realise mmyolo on mmdetection?

**Comment by xin-li-67** [comment]
> Add quantization for MMYOLO will be a great feature. YOLO is already fast and relatively accurate. But, with quantization techniques (like Int8, ...), it will be much more powerful !

Hi~ Based on my knowledge, you may find some quantization demos in MMDeploy, as in most scenarios, I believe people will use weight quantization while deploying the models. Meanwhile, MMRazor supports the distillation and sparsification algorithms.

**Comment by mohamedrekik** [comment]
> Hi~ Based on my knowledge, you may find some quantization demos in MMDeploy, as in most scenarios, I believe people will use weight quantization while deploying the models. Meanwhile, MMRazor supports the distillation and sparsification algorithms.

@xin-li-67 Thanks for your reply. AFAIK, MMDeploy doesn't support MMYOLO and I couldn't find any demo/documentation/code in MMRazor that works on YOLOv8. Feel free to correct me if I am wrong.

**Comment by PriyanshuPandeyNA** [comment]
Hello @hhaAndroid !, Can you help me out with the support of yolox-ins-head!

**Comment by hiyyg** [comment]
Any plan to add YOLOv10?
